apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emby-ingress
  namespace: media
  annotations:
    tailscale.com/expose: "true"
spec:
  ingressClassName: tailscale
  rules:
  - host: emby.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emby
            port:
              name: http
  tls:
    - hosts:
        - emby.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: media
  annotations:
    tailscale.com/expose: "true"
spec:
  ingressClassName: tailscale
  rules:
  - host: jellyfin.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              name: http
  tls:
    - hosts:
        - jellyfin.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: sonarr.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              name: http
  tls:
    - hosts:
        - sonarr.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-4k-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: sonarr-4k.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr-4k
            port:
              name: http
  tls:
    - hosts:
        - sonarr-4k.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: radarr.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              name: http
  tls:
    - hosts:
        - radarr.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-4k-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: radarr-4k.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr-4k
            port:
              name: http
  tls:
    - hosts:
        - radarr-4k.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: prowlarr.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              name: http
  tls:
    - hosts:
        - prowlarr.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: qbitt.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              name: http
  tls:
    - hosts:
        - qbitt.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr-ingress
  namespace: media
  annotations:
    # tailscale.com/expose: "true"
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
  - host: jellyseerr.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseerr
            port:
              name: http
  tls:
    - hosts:
        - jellyseerr.dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
  namespace: media
spec:
  ingressClassName: tailscale
  rules:
  - host: bazarr.dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              name: http
  tls:
    - hosts:
        - bazarr.dns
